theme: jekyll-theme-minimal
logo: /assets/img/airportjs.png
title: Aiport Autocomplete Package
description: A lightweight implementation of aiport picker. The airport data are up-to-date and are scraped from OpenFlights (https://openflights.org/data.html) .
